args:
  image2video: True 
  latent_channels: 16
  mode: inference

  load: ./pretrained_models/mtv/multi
  
  batch_size: 1
  input_type: txt
  sampling_image_size: [480, 720]
  sampling_num_frames: 13  
  sampling_fps: 24
  bf16: True 
  force_inference: True
  sample_rate: 16000
  wav2vec_model_path: ./pretrained_models/wav2vec2-base-960h